config/routes.rb
Proba::Application.routes.draw do

  root to: 'file_parsers#home'
  match '/upload', to: 'file_parsers#upload'
  match '/parse', to: 'file_parsers#parse'

  get "file_parsers/parse"

  get "file_parsers/upload"

end

app/models/file_parser.rb
require './lib/parser/tokenizer'
require './lib/parser/parser'
class FileParser < ActiveRecord::Base
  # attr_accessible :title, :body
  
  def self.parse_text(text)
      
      parser = Parser.new
      parser.build_tree
      
      Tokenizer.tokenize(text).each do |token|
        unless parser.feed_token token
          break
        end
      end
      parser.messages
    end
end

app/models/text_file.rb
class TextFile < ActiveRecord::Base
  # attr_accessible :title, :body
  
  def self.save(file, name)
    name = "./public/" + name
    File.open(name, "wb") { |f| f.write(file.read) }
  end
  
  def self.result_to_file(name,result)
    name = "./public/" + name
    File.open(name, "wb") { |f| f.write(result)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/file_parsers_controller.rb
class FileParsersController < ApplicationController
  def home
  end

  def parse
    unless File.exist?('./public/up_file.txt')
      render 'home'
    end
    text = File.read('./public/up_file.txt')
    @messages = FileParser.parse_text(text)
    if @messages[:error].blank?
      TextFile.result_to_file('result.txt',@messages[:success])
      flash.now[:notice] = "Success! File saved to public folder. Result: " + @messages[:success]
    else
      flash.now[:error] = "Failiure! " + @messages[:error] + ". You should upload a new file"
    end
  end

  def upload
    if params[:upload].nil?
      flash.now[:error] = "No file selected"
      render 'home'
    else
      TextFile.save(params[:upload]['textfile'],'up_file.txt')
      flash.now[:notice] = "File uploaded"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_parsers_helper.rb
module FileParsersHelper
end

app/views/file_parsers/home.html.erb
<h1>File Upload for technical interview app</h1>
<%= form_for :upload, :url => { :action => 'upload' }, :multipart => true do |f| %>
  <%= f.file_field :textfile %>
  <%= f.submit "Upload" %>
<% end %>

app/views/file_parsers/parse.html.erb
<div class="center hero-unit">
  <h1>Formal language interpreter</h1>
  <%= link_to "Upload new file", :root, class: "btn btn-large btn-primary" %>
</div>

app/views/file_parsers/upload.html.erb
<div class="center hero-unit">
  <h1>Formal language interpreter</h1>
  <%= link_to "Parse text file", parse_path, class: "btn btn-large btn-primary" %>
  <%= link_to "Upload new file", :root, class: "btn btn-large btn-primary" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proba</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>